Uncomment workflow steps in building blocks YAML

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,18 +1,18 @@
-# name: 01 - Building blocks
-# on: push
+name: 01 - Building blocks
+on: workflow_dispatch
 
-# jobs:
-#     echo-hello:
-#         runs-on: ubuntu
-#         steps:
-#             - name: hello world
-#               run: echo "Hello world"
-#     echo-goodbye:
-#         runs-on: ubuntu:latest
-#         steps:
-#             - name: "Failed step"
-#               run: |
-#                 echo "I will fail"
-#                 exit 1
-#             - name: Say goodbye
-#               run: echo "Say goodbye"
+jobs:
+    echo-hello:
+        runs-on: ubuntu
+        steps:
+            - name: hello world
+              run: echo "Hello world"
+    echo-goodbye:
+        runs-on: ubuntu:latest
+        steps:
+            - name: "Failed step"
+              run: |
+                echo "I will fail"
+                exit 1
+            - name: Say goodbye
+              run: echo "Say goodbye"
